server:
  port: 8090
  session:
    timeout: 7200

spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dsmp?zeroDateTimeBehavior=convert_to_null&useSSL=false&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=Hongkong
#    url: jdbc:mysql://192.168.1.7:3306/dsmp?zeroDateTimeBehavior=convert_to_null&useSSL=false&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=Hongkong
    username: root
    password: root123456
    
 mail:
    host: mail.cbsdata.co.jp
    username: sou@cbsdata.co.jp
    password: p@ssw0rd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          port: 587
          starttls:
            enable: true
          ssl:
            trust: mail.cbsdata.co.jp
    from: sou@cbsdata.co.jp
    default-encoding: utf-8  
    debug: false
    
mybatis:
  type-aliases-package: com.cbs.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  
preread: 
   uploadPath: c:/image/

